on:
  push:
    branches: [ main ]
  workflow_dispatch:
concurrency:
  group: generate-jldec-uk
jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      DOMAIN: jldec.uk

    steps:
    - name: checkout source repo
      uses: actions/checkout@v4

    - name: checkout destination repo under ./out
      uses: actions/checkout@v4
      with:
        repository: jldec/jldec.uk
        token: ${{ secrets.GH_TOKEN }}
        path: out

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: generate output
      run: |
        pnpm install
        pnpm generate
        cd out
        git config user.email "jldec@ciaosoft.com"
        git config user.name "cloudflare-pages-test generate action"
        git add -A
        if ! git diff-index --quiet HEAD ; then git commit -m 'https://github.com/jldec/cloudflare-pages-test/actions/runs/${{ github.run_id }}' && git push ; fi
        echo done
